version: 1.0.0
services:
  - mysql
events:
  build:
    steps:
      -
        composer:
          type: script
          script:
            - 'composer install --no-interaction'
            - 'mysql -u root -proot -e "CREATE DATABASE drupal"'
            - 'cd docroot'
            - '/usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../vendor/bin/drush site-install -y --db-url=mysql://root:root@127.0.0.1:3306/drupal'
            - 'php -S 127.0.0.1:8081 &'
            - 'sleep 2'
            - 'cd ..'
            - ./vendor/bin/behat
variables:
  global:
    VALIDATION_TOKEN:
      secure: 2acfIynfp734BVEt7dyeeacJxZiMPl0SBUMz9k0gWbWvHrrpBgshuIA3BsEhLfM/RwiMmaYjxv9f0ndYcr4K5SlxJlydGLGwEVb5pOFEbhVqnhBjm369TLpYW9Z3Q9VNK19vHs/suYVCtF1IGaL+P4xT/WgiR+Jk+ctJytDYWHHOj/F3cnJumzcRVAovch+nIKGcNAVO0HCCcFmqzoVrTl6PcYQWnVN8CcrnL/BWDtNuCxM5cNmnd9Yi1Nlr/uIEZC6bQcqGC9NF8Gpx302cnzp0EaWLlIKaGt0u7mHEjL9E4WXmJVPIlKuoQ9Z9Jn2RyKke3kZAg+2xitr/FKUiQghYywUW6FJeGgHschpKSt213e0LQlcxUXbcfcy5rmUOFVkmTa08ngM/vFfZhUJ2QlNI1+jBw8elYQMBEusPO9QUPfXYkFE2ryUwpEiPu3IKNEAJ2oKiNgaEl6+1U6k4gjE98VTYvvirAOaq1bi3AB+zvNs820FCLnJm4nuZeanDExcreKWUhg/Mtbm7xLmlIdRLxETfv+dVJ+ciSQybzX0YPQevz8GTFOWErKsX14RkyqUsbtpIqy5vXE4L7TzZeBqV3LAt2FQPwADHqY2a0wzdEVgks0+GuwsDySFP0CCKHsq8t/awiouJzhX2LkZ36mShoO1vC3Q8LuH1NtlL+rnYac=8rhS4s3Jd7/apYNHxSh7UXzhjamSLMqk+ht49aQw7Mi8UG4bbx/JeHoiK7Gokzm/
    EMAIL:
      secure: 2aceWjzmylJWAJwVsQjlbFjfpxFVvABeAacIXqVrQFz1r8+G7+eHLrtPxqcU4L8rShqJpGe9ZDKaOV+uHmh4Ss9tS90abWZuiGZJKPn/golO85eXZs2OxNJ43lz6U3fLqNr1PQTUApMQHtCPYDP9dDbWyzBEu86GwucnarsRPCaozb8fk6B8GJPcb3um/SER3HvQaQGeDgu7UKRykt+vkSPaK7HNjYeOY80iKiOaeSDrNGKQGpZMT2VRJy+XOoX3IJNONx3o4iPqAANYuf8jusKt6TLR5k0x8I7fPElcsAwlr63po+XOa0ZFO60uObdi1Fn8yUVttXR8cxPFDbMUT9l39SmiIyL+glDE02tSmJKarQ1vex3s9fd0k2Tcxms5jhUaJqVwRq/MuicEet/MYwYcPm5v35IYS/GoN7FonoTBxiVyEuSBJRbNbYLRrjOocGb2Q0ImkmyNLwuchryx5+9yBAsleKc3usKZ0LWsUMSQFOPv6RZWrgoM6hqSp8OgCQl9+blAtCIY0aR+F8EMzRKpD8JpZza9ABlvQ8T6/PIf7B8kPb9qLMzuGSNAH45oktg9T/WEzOOruAmVqF1tjB2oS0vSGY/TGg4kCZKk3ltWUu4oUHBB3rBI6de9S1eIclgzCEbZ3A6t3PcKU5sZc6J+1Zm6Tf7B+jJJkneSNuWvA8=Vq/VNn71rZ6NAp77dYnKxfwn1Nyo5M8paPowqRKFSss=
